# fly.toml app configuration file generated for hack-united-server on 2024-01-13T17:34:55+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hack-united-server"
primary_region = "otp"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 512
