name: Build and deploy Node.js app to Azure Web App - hack-united-web-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          cd server
          npm install -g @nestjs/cli
          npm i
          npm install typescript
          npx prisma generate
          npx tsc
          cp -r node_modules ./dist

      - name: Zip artifact for deployment
        run: zip -r release.zip ./dist/*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip ./node-app/release.zip -d ./server

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A07ADB3F0F124145AAE59E3A3D5E3595 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D2477FA851244621A44B11070A2F4B3C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C79D63ABB9C24888A9276E0A964652A5 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hack-united-web-app'
          slot-name: 'Production'
          package: './server/dist'
